# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zn-2mHReZH5zsC3d0JTL2d9rvJgVETiu
"""

!pip install flask_ngrok
!pip install pyngrok==4.1.1
!ngrok authtoken  2P4ml48BFhmvlCcJwEqVKfXxjZb_Jw7Uou9kbAqnrPewv9YA

from google.colab import drive
drive.mount('/content/gdrive')
from google.colab import files

files.upload()

from flask_ngrok import run_with_ngrok
from flask.templating import render_template
from flask import Flask 
from flask import request
from proceso_cuenta import crear_cuentas
cuentas=crear_cuentas()


template_folder='/content/drive/MyDrive/Colab Notebooks/proyecto_final/template'

app= Flask(__name__, template_folder = template_folder)
run_with_ngrok(app)

@app.route("/")

@app.route('/home')
def home():
 return render_template('home.html')

@app.route('/procesar',methods= ['POST'])
def procesar_formulario():
  dni = request.form['dni']
  saludo_dni = cuentas.get(dni).saludo()
  return render_template('home.html',saludo = saludo_dni)

@app.route("/")
@app.route("/proceso_archivos")

def proceso_archivos():
   return render_template('proceso_archivos.html')

@app.route('/movimiento', methods=['POST'])
def procesar_deposito():
  monto= request.form['monto']
  cuentas.get(dni).aplicar_deposito(monto)
  return render_template('proceso_archivos.html')
 
def procesar_extraccion():
  monto=request.form['monto']
  cuentas.get(dni).aplicar_gastos(monto)
  return render_template('proceso_archivos.html')
 
def procesar_transferencia():
  monto=request.form['monto']
  cuentas.get(dni).aplicar_transferencia(monto)
  return render_template('proceso_archivos.html')

app.run()