# -*- coding: utf-8 -*-
"""persona.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1amSaq7Q_yciRmRGjvMbaZU00yUiu-u-o
"""

#!/usr/bin/env python
# -*- coding: utf-8 -*-
# author: <Juana Regert>

"""
creando clase Persona

"""
import datetime
from datetime import date
from cuenta import Cuenta

def calcular_edad(fecha_nacimiento):#metodo para calcular la edad
  anio = int (fecha_nacimiento[0:4])
  mes = int (fecha_nacimiento[5:7])
  dia = int (fecha_nacimiento[8:10])
  today = date.today()
  edad =( int(today.year) - anio)
  if mes >= int(today.month):
   if dia > int(today.day):
      return (edad-1)
   elif dia <= int(today.day):
        return edad
   else:
     return(edad)

class Persona():

   def __init__ (self, dni, nombre, fecha_nacimiento):#constructor de Persona 
      self.dni = dni
      self.nombre = nombre
      self.edad = calcular_edad(fecha_nacimiento)
      self.cuentas = []

   def _str_(self):
     return f" nombre: {self.nombre} "

   def crear_cuenta(self):#verificacion de edad para crear cuenta Joven o cuenta comun
     if self.edad >=18 and self.edad <= 30:
        cuenta = CuentaJoven()
        self.cuenta.append(cuenta)
     elif self.edad >30:
         cuenta = Cuenta()
         self.cuentas.append(cuenta)
     else:
       print("Error, la persona es menor de edad")

   def obtener_movimiento(self):
     todos_los_movimientos = []
     for cuenta in self.cuenta:
       todos_los_movimientos += cuenta.movimiento
       return todos_los_movimientos

   def saludo(self):#metodo con saludo dependiendo la hora
     tiempo = datetime.datetime.now()
     hora = time.strftime("%H",time.localtime())
     manana = ",Buenos Dias!"
     tarde = ",Buenas Tardes!"
     noche = ",Buenas Noches!"
     if hora < "12":
       print("Hola,",self.nombre,manana,"{}:{}".format(tiempo.hour,tiempo.minute),"hs","-","self.ciudad","-")
     elif hora >"12"  and hora < "18":
       print("Hola,",self.nombre,tarde,"{}:{}".format(tiempo.hour,tiempo.minute),"hs","-","self.ciudad","-")
     elif hora > "18":
      print("Hola,", self.nombre,noche,"{}:{}".format(tiempo.hour,tiempo.minute),"hs","-","self.ciudad","-")